apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adam-insight-customer-context-agent.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  agent-config.env: |
    XIPHOS_URL: {{ .Values.xiphos.baseUrl | quote }}
    CUSTOMER_API_URL: {{ .Values.customerApi.baseUrl | quote }}
    CHAKRA_RS_URL: {{ .Values.chakraRs.baseUrl | quote }}
    CA_CRT_PATH:  "/run/certs/spock-ca/ca.crt"
    TLS_CRT_PATH: "/run/certs/spock-tls/tls.crt"
    TLS_KEY_PATH: "/run/certs/spock-tls/tls.key"